name: learnest_fresh
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # 国际化与语言
  flutter_localizations:
    sdk: flutter
  intl: any

  # 状态管理
  provider: any

  # 核心服务
  http: any
  shared_preferences: any
  flutter_dotenv: any
  supabase_flutter: any

  # UI 资产
  flutter_svg: any
  lottie: any
  fl_chart: any
  confetti: any
  
  # 数学逻辑
  math_expressions: any
  flutter_math_fork: any

  # 相机与图像处理
  camera: any
  image_picker: any
  image: any
  path_provider: any
  path: any
  
  # 系统权限
  permission_handler: any
  device_info_plus: any
  app_settings: any
  
  # 分享与通知
  share_plus: any
  flutter_local_notifications: any
  timezone: any

  # 数据库存储
  sqflite: any
  hive: any
  hive_flutter: any
  crypto: any
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    # ✅ 暂时注释掉报错的路径，等以后文件夹里有文件了再放开
    # - assets/images/
    # - assets/icons/
    # - assets/lottie/
    # - assets/svg/

  # ✅ 字体同理，如果物理路径 assets/fonts/ 里还没放这些 ttf 文件，必须注释掉
  # fonts:
  #   - family: Tesla 
  #     fonts:
  #       - asset: assets/fonts/tesla.ttf
  #   - family: DIN
  #     fonts:
  #       - asset: assets/fonts/din_bold.ttf
  #         weight: 700